DROP table IF EXISTS logistics_user;
DROP table IF EXISTS logistics_rlorder;
DROP table IF EXISTS logistics_rlorder_item;
DROP table IF EXISTS logistics_orderFile;
DROP table IF EXISTS logistics_file;
DROP table IF EXISTS logistics_trackingno;
DROP table IF EXISTS logistics_logistics;
DROP table IF EXISTS logistics_sku;
#delete from logistics_rlorder where id >= 11427;
#delete from logistics_sku;